# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('priority', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')])),
                ('color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='VendorListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateServing', models.DateField(null=True)),
                ('Name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=60)),
                ('zipCode', models.IntegerField()),
                ('beginning', models.CharField(max_length=60)),
                ('ending', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=69)),
                ('userlocation', models.CharField(max_length=120)),
            ],
        ),
    ]
